//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleChaper4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleChaper4.Resources.Site", typeof(Site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About page.
        /// </summary>
        public static string About_Message {
            get {
                return ResourceManager.GetString("About_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is a demo application. Authentication is not implemented.
        /// </summary>
        public static string Login_Message {
            get {
                return ResourceManager.GetString("Login_Message", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Return to Home.
        /// </summary>
        public static string Login_ReturnHome {
            get {
                return ResourceManager.GetString("Login_ReturnHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Menu_Login {
            get {
                return ResourceManager.GetString("Menu_Login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Menu_Logout {
            get {
                return ResourceManager.GetString("Menu_Logout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Admin Area.
        /// </summary>
        public static string Admin_Title {
            get {
                return ResourceManager.GetString("Admin_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This is the Admin area Index page.
        /// </summary>
        public static string Admin_Welcome {
            get {
                return ResourceManager.GetString("Admin_Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string Admin_BackToHome {
            get {
                return ResourceManager.GetString("Admin_BackToHome", resourceCulture);
            }
        }
    }
}